name: Synchronize to p-l-r-api

on:
  push:
    branches:
      - public_main
    paths-ignore:
      - '**/README.md'
      - '**/docs/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.API_TOKEN_FOR_PLR_API }}

      - name: Push to Destination Repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.API_TOKEN_FOR_PLR_API }}
          directory: '.'
          repository: 'juanmgomez7152/p-l-r-api'
          branch: 'main'
          force_with_lease: true